const state={detail:null,preview:null,queueNext:''};
const $=s=>document.querySelector(s);const uid=()=>crypto.randomUUID();
function notice(message,bad=false){const n=$('#notice');n.textContent=message;n.style.background=bad?'#7d3326':'#15251e';n.classList.add('show');setTimeout(()=>n.classList.remove('show'),3500)}
async function api(path,options={}){const headers=options.body?{'Content-Type':'application/json',...(options.headers||{})}:options.headers;const res=await fetch(path,{...options,headers});const body=await res.json();if(!res.ok)throw new Error(body.error?.message||'请求失败');return body}
function meta(actor){return{expectedVersion:state.detail.batch.version,idempotencyKey:uid(),actor:actor||prompt('请输入当前操作者')||''}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function localDateTime(value){const date=new Date(value),offset=date.getTimezoneOffset()*60000;return new Date(date-offset).toISOString().slice(0,16)}
async function load(id){state.detail=await api(`/api/v1/batches/${encodeURIComponent(id)}`);state.preview=null;render();localStorage.setItem('lastBatch',id)}
function render(){
  const d=state.detail,b=d.batch,draft=b.status==='draft';$('#workspace').classList.remove('hidden');$('#batch-title').textContent=`${b.speciesName} · ${b.id}`;$('#batch-status').textContent=`${b.status} / v${b.version}`;
  const sf=$('#source-form');for(const name of ['speciesName','collectionSite','permitDigest','owner'])sf.elements[name].value=b[name];sf.elements.collectedAt.value=localDateTime(b.collectedAt);sf.querySelectorAll('input,button').forEach(x=>x.disabled=!draft);
  $('#preflight').innerHTML=d.preflight.canSubmit?'<span class="ok">预检通过，可以提交</span>':`<ul>${d.preflight.blockers.map(x=>`<li><strong>${esc(x.field)}</strong>：${esc(x.message)}</li>`).join('')}</ul>`;
  const sum=d.packetSummary;$('#packet-summary').textContent=`${sum.packetCount} 单元 / ${sum.totalSeedCount} 粒 / ${sum.totalNetWeightGrams} g`;
  $('#packet-list').innerHTML=d.packets.map(p=>`<div class="item"><strong>${esc(p.containerCode)}</strong><p>${p.seedCount} 粒 · ${p.netWeightGrams} g · 初始含水率 ${p.initialMoisturePercent}%</p><p>${esc(p.sourceNote)}</p>${draft?`<div class="inline"><button data-edit-packet="${p.id}">编辑</button><button data-delete-packet="${p.id}" class="danger">删除</button></div>`:''}</div>`).join('')||'<p>尚无分装单元。</p>';
  $('#test-form select[name=packetId]').innerHTML=d.packets.map(p=>`<option value="${p.id}">${esc(p.containerCode)}</option>`).join('');
  $('#assessment-list').innerHTML=d.assessmentChains.map(c=>`<div class="chain"><strong>${esc(d.packets.find(p=>p.id===c.packetId)?.containerCode||c.packetId)} · ${c.assessmentType}</strong>${c.records.map(t=>`<div class="item ${t.result==='fail'?'problem':''} ${t.isEffective?'effective':''}"><strong>${t.result}${t.isEffective?' · 当前有效':' · 已替代'}</strong><p>${esc(t.operator)} / ${new Date(t.performedAt).toLocaleString()}</p><p>${t.supersedesId?`替代 ${esc(t.supersedesId)}`:'首次试验'}</p></div>`).join('')}</div>`).join('')||'<p>尚无试验记录。</p>';
  $('#issue-list').innerHTML=d.issues.map(issueHTML).join('')||'<p>未发现结构化问题。</p>';
  $('#digest').textContent=b.manifestDigest?`冻结摘要：${b.manifestDigest}`:'清单尚未冻结。';$('#certificate').innerHTML=d.certificate?`<div class="item"><strong>${d.certificate.certificateNumber}</strong><p>校验码 ${d.certificate.verificationCode}</p><a target="_blank" href="/certificates/${d.certificate.certificateNumber}/print?code=${d.certificate.verificationCode}">打开打印视图</a></div>`:'';
  $('#packet-form').querySelectorAll('input,button').forEach(x=>x.disabled=!draft);$('#submit-batch').disabled=!d.preflight.canSubmit;$('#test-form').querySelectorAll('input,select,button').forEach(x=>x.disabled=!['submitted','remediation'].includes(b.status));$('#review-batch').disabled=!d.progress.canApproveReview;$('#batch-remediation').disabled=!d.issues.some(i=>['open','returned'].includes(i.status));$('#preview-freeze').disabled=b.status!=='reviewed';$('#freeze-batch').disabled=!state.preview||state.preview.batchVersion!==b.version;$('#issue-certificate').disabled=b.status!=='frozen';syncSupersedes();renderPreview();
}
function passingEvidence(issue){const type=issue.code.startsWith('MOISTURE_')?'moisture':'germination';return state.detail.assessments.filter(t=>t.packetId===issue.packetId&&t.assessmentType===type&&t.isEffective&&t.result==='pass')}
function issueHTML(i){const review=i.status==='pending_review'?`<div class="inline"><button data-review="${i.id}" data-accept="true">接受</button><button data-review="${i.id}" data-accept="false">退回</button></div>`:'';const editable=['open','returned'].includes(i.status);const choices=passingEvidence(i).map(t=>`<option value="${t.id}">${t.id}</option>`).join('');return`<div class="item problem"><label class="issue-check"><input type="checkbox" data-issue-select="${i.id}" ${editable?'':'disabled'}><strong>${esc(i.code)} · ${esc(i.status)}</strong></label><p>${esc(i.message)}</p>${editable?`<label>整改说明<textarea data-issue-note="${i.id}" maxlength="500"></textarea></label><label>有效合格复测<select data-issue-evidence="${i.id}"><option value="">不选择</option>${choices}</select></label>`:`<p>${esc(i.remediationNote||'尚无整改说明')}</p>`}${review}</div>`}
function syncSupersedes(){const f=$('#test-form'),packet=f.elements.packetId.value,type=f.elements.assessmentType.value,tail=state.detail?.assessments.find(t=>t.packetId===packet&&t.assessmentType===type&&t.isEffective);f.elements.supersedesId.value=tail?.id||''}
function renderPreview(){const p=state.preview;if(!p){$('#freeze-preview').innerHTML='';return}$('#freeze-preview').innerHTML=`<div class="preview"><p><strong>版本 v${p.batchVersion}</strong> · ${p.summary.packetCount} 单元 / ${p.summary.totalSeedCount} 粒 / ${p.summary.totalNetWeightGrams} g</p><p class="digest">${p.digest}</p>${p.manifest.packets.map(x=>`<p>${esc(x.containerCode)}：${x.seedCount} 粒，${x.netWeightGrams} g，含水率 ${x.latestMoisturePercent}%，萌发率 ${x.germinationRate}%</p>`).join('')}</div>`}
$('#create-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const batch=await api('/api/v1/batches',{method:'POST',body:JSON.stringify({expectedVersion:0,idempotencyKey:uid(),actor:f.get('actor'),speciesName:f.get('speciesName'),collectionSite:f.get('collectionSite'),collectedAt:new Date(f.get('collectedAt')).toISOString(),permitDigest:f.get('permitDigest'),owner:f.get('owner')})});$('#lookup-id').value=batch.id;await load(batch.id);await loadQueue();notice('草拟批次已创建')}catch(x){notice(x.message,true)}});
$('#lookup-form').addEventListener('submit',async e=>{e.preventDefault();try{await load($('#lookup-id').value.trim())}catch(x){notice(x.message,true)}});
$('#source-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api(`/api/v1/batches/${state.detail.batch.id}/source`,{method:'PATCH',body:JSON.stringify({...meta(f.get('actor')),speciesName:f.get('speciesName'),collectionSite:f.get('collectionSite'),collectedAt:new Date(f.get('collectedAt')).toISOString(),permitDigest:f.get('permitDigest'),owner:f.get('owner')})});await load(state.detail.batch.id);notice('来源修订已保存，版本和预检已刷新')}catch(x){notice(x.message,true)}});
$('#packet-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api(`/api/v1/batches/${state.detail.batch.id}/packets`,{method:'POST',body:JSON.stringify({...meta(),containerCode:f.get('containerCode'),seedCount:+f.get('seedCount'),netWeightGrams:+f.get('netWeightGrams'),initialMoisturePercent:+f.get('initialMoisturePercent'),sourceNote:f.get('sourceNote')})});await load(state.detail.batch.id);e.target.reset();notice('分装单元已登记')}catch(x){notice(x.message,true)}});
$('#packet-list').addEventListener('click',async e=>{const edit=e.target.dataset.editPacket,remove=e.target.dataset.deletePacket;if(!edit&&!remove)return;const p=state.detail.packets.find(x=>x.id===(edit||remove));try{if(remove){if(!confirm(`确认删除 ${p.containerCode}？`))return;await api(`/api/v1/batches/${p.batchId}/packets/${p.id}`,{method:'DELETE',body:JSON.stringify(meta())})}else{const containerCode=prompt('容器标识',p.containerCode);if(containerCode===null)return;await api(`/api/v1/batches/${p.batchId}/packets/${p.id}`,{method:'PUT',body:JSON.stringify({...meta(),containerCode,seedCount:+prompt('种子数量',p.seedCount),netWeightGrams:+prompt('净重（克）',p.netWeightGrams),initialMoisturePercent:+prompt('初始含水率（%）',p.initialMoisturePercent),sourceNote:prompt('来源备注',p.sourceNote)||''})})}await load(p.batchId);notice(remove?'分装单元已删除':'分装单元已修订')}catch(x){notice(x.message,true)}});
$('#submit-batch').addEventListener('click',()=>simple('submit','来源与分装清单已锁定'));
$('#test-form').addEventListener('change',syncSupersedes);$('#test-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),type=f.get('assessmentType');try{await api(`/api/v1/batches/${state.detail.batch.id}/assessments`,{method:'POST',body:JSON.stringify({...meta(),packetId:f.get('packetId'),test:{assessmentType:type,sampleSize:type==='germination'?+f.get('sampleSize'):0,germinatedCount:type==='germination'?+f.get('germinatedCount'):0,moisturePercent:type==='moisture'?+f.get('moisturePercent'):0,performedAt:new Date().toISOString(),operator:f.get('operator'),supersedesId:f.get('supersedesId')}})});await load(state.detail.batch.id);await loadQueue();notice('试验已写入有效替代链')}catch(x){notice(x.message,true)}});
$('#batch-remediation').addEventListener('click',async()=>{const selected=[...document.querySelectorAll('[data-issue-select]:checked')];if(!selected.length){notice('请至少勾选一个问题',true);return}const items=selected.map(x=>({issueId:x.dataset.issueSelect,note:document.querySelector(`[data-issue-note="${x.dataset.issueSelect}"]`).value,evidenceAssessmentId:document.querySelector(`[data-issue-evidence="${x.dataset.issueSelect}"]`).value}));try{await api(`/api/v1/batches/${state.detail.batch.id}/issues/remediation`,{method:'POST',body:JSON.stringify({...meta(),items})});await load(state.detail.batch.id);await loadQueue();notice('批量整改已原子提交')}catch(x){notice(x.message,true)}});
$('#issue-list').addEventListener('click',async e=>{const id=e.target.dataset.review;if(!id)return;try{const note=prompt('复核意见');await api(`/api/v1/batches/${state.detail.batch.id}/issues/${id}/review`,{method:'POST',body:JSON.stringify({...meta(),accept:e.target.dataset.accept==='true',note})});await load(state.detail.batch.id);await loadQueue();notice('问题复核结果已记录')}catch(x){notice(x.message,true)}});
$('#review-batch').addEventListener('click',async()=>{const note=prompt('批次复核意见');try{await api(`/api/v1/batches/${state.detail.batch.id}/review`,{method:'POST',body:JSON.stringify({...meta(),note})});await load(state.detail.batch.id);await loadQueue();notice('批次已通过独立复核')}catch(x){notice(x.message,true)}});
$('#preview-freeze').addEventListener('click',async()=>{try{state.preview=await api(`/api/v1/batches/${state.detail.batch.id}/freeze-preview`);renderPreview();$('#freeze-batch').disabled=false;notice('冻结清单预览与摘要已生成')}catch(x){notice(x.message,true)}});
$('#freeze-batch').addEventListener('click',async()=>{if(!state.preview)return;try{await api(`/api/v1/batches/${state.detail.batch.id}/freeze`,{method:'POST',body:JSON.stringify({...meta(),batchVersion:state.preview.batchVersion,previewDigest:state.preview.digest})});await load(state.detail.batch.id);notice('预览摘要一致，保存清单已原子冻结')}catch(x){notice(x.message,true)}});
$('#issue-certificate').addEventListener('click',()=>simple('certificate','不可变入藏凭据已签发'));
async function simple(action,message){try{await api(`/api/v1/batches/${state.detail.batch.id}/${action}`,{method:'POST',body:JSON.stringify(meta())});await load(state.detail.batch.id);await loadQueue();notice(message)}catch(x){notice(x.message,true)}}
function queueQuery(cursor=''){const f=new FormData($('#queue-form')),q=new URLSearchParams();for(const name of ['speciesName','owner','severity','issueStatus','sort','pageSize']){const value=f.get(name);if(value)q.set(name,value)}if(cursor)q.set('cursor',cursor);return q.toString()}
async function loadQueue(cursor=''){try{const result=await api('/api/v1/review-queue?'+queueQuery(cursor));state.queueNext=result.nextCursor||'';$('#queue-next').disabled=!state.queueNext;$('#queue-stats').textContent=`${result.stats.batchCount} 个批次 · ${result.stats.pendingReviewIssueCount} 项待复核 · ${result.stats.approvableBatchCount} 个可批准 · ${result.stats.seriousIssueBatchCount} 个含严重问题`;$('#queue-list').innerHTML=result.items.map(x=>`<button class="queue-item" data-open-batch="${x.batch.id}"><strong>${esc(x.batch.speciesName)} · ${esc(x.batch.owner)}</strong><span>${x.pendingReviewCount} 待复核 / ${x.returnedCount} 退回 / ${x.unclosedSeriousCount} 严重未关闭 / ${x.qualifiedPacketCount} 合格单元</span></button>`).join('')||'<p>没有匹配的待办批次。</p>'}catch(x){notice(x.message,true)}}
$('#queue-form').addEventListener('submit',e=>{e.preventDefault();loadQueue()});$('#queue-next').addEventListener('click',()=>loadQueue(state.queueNext));$('#queue-list').addEventListener('click',e=>{const button=e.target.closest('[data-open-batch]');if(button)load(button.dataset.openBatch)});
const last=localStorage.getItem('lastBatch');if(last)$('#lookup-id').value=last;loadQueue();
